apiVersion: apps/v1
kind: Deployment
metadata:
  name: itdt-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itdt-frontend
  template:
    metadata:
      labels:
        app: itdt-frontend
    spec:
      containers:
      - name: itdt-frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: "Andrey Zinchenko"
        - name: REACT_APP_COMPANY_NAME
          value: "Top Da World Inc."
        ports:
        - containerPort: 3000