apiVersion: v1
kind: Service
metadata:
  name: itdt-frontend-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: itdt-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000